### ISSUE TITLE
Send sql commands without preparing them

### ISSUE THREAD

**Issue by gabrielschuck** [LegitSoulja/SlickInject#14]
Hello. I needed to have a function in the slickinject class to send sql commands without preparing them. the reason is that I want to start working with event creation in mysql, but this function is not supported with the prepared statements.

**Comment by LegitSoulja** [comment]
@gabrielschuck 

Hey, **SlickInject** has discontinued because it was only for personal use and wasn't fully extended to provide full additional support. However, a friend of mines @Andrews54757 has developed a similar project called **[SuperSQL](https://github.com/ThreeLetters/SuperSQL)** that works exactly like **SlickInject**, however much more advanced, and just better over all he must say. Give it a shot.


The first version of **SlickInject** that was made wasn't using prepare/execute and was removed from the releases. Luckily, I still have that backup if you would like to work with that instead. It's secure (As of using a real escape method), but it's not recommended. [SlickInjectV1_build.zip](https://github.com/LegitSoulja/SlickInject/files/1347906/SlickInjectV1_build.zip)

> **P.S**: In that zip file, I compiled/built SlickInject into 1 file in build.php. That's all you'll need, as the SlickInject class is global.
